runtime: go
api_version: go1

service: gamify-halloween
handlers:
  # All URLs are handled by the Go application script
  - url: /api/.*
    script: _go_app
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /(.*)
    static_files: static/\1
    upload: static/(.*)

env_variables:
  PROJECT_ID: "uplifted-elixir-203119"
  DATASTORE_KIND: "gamify-halloween"
  GOOGLE_APPLICATION_CREDENTIALS: "./key.json"
  KEYRING: "gamify"
  CRYPTO_KEY: "halloween"
  LOCATION: "us-west1"
  SALT: "CiQAavWm7J3J4BLJ4fRVNk1zt+A/JYycazI5BtB0qGuqG5BzAVUSTAB0deS58PdiymbOC8f4WVChXHfrRB28+vC2JN8U4P5lQPTtQua+IiDBsaxtI60h7tVPVX+xYcfriYlIqn2Z3s+M/vKf5akQzxtfMbQ="
